In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
pd_rawdata = pd.read_csv('전국소방용수시설표준데이터.csv', encoding='cp949')

print(pd_rawdata.columns)
column_selection = ['시도명', '소재지도로명주소', '위도', '경도']
hydrant_data = pd_rawdata[column_selection]
print(hydrant_data.head())

Index(['시설번호', '시설유형코드', '시도명', '시군구명', '시군구코드', '소재지도로명주소', '소재지지번주소', '위도',
       '경도', '상세위치', '안전센터명', '보호틀유무', '설치연도', '출수압력', '관할기관명', '관할기관전화번호',
       '데이터기준일자', '제공기관코드', '제공기관명'],
      dtype='object')
     시도명                            소재지도로명주소         위도          경도
0  서울특별시  서울특별시 금천구 가산디지털2로 36 g밸리 더리브 스마트타워  37.471257  126.882859
1  서울특별시           서울특별시 금천구 가산디지털1로 171 수위실  37.481101  126.881118
2  서울특별시         서울특별시 금천구 두산로3길 49 가산동제2경노당  37.472620  126.888857
3  서울특별시               서울특별시 금천구 벚꽃로 208 경비실  37.473484  126.886718
4  서울특별시           서울특별시 금천구 가산디지털2로 169 수위실  37.482797  126.877303

In [8]:
pd_rawdata = pd.read_csv('전국소방자동차전용구역표준데이터.csv', encoding='cp949')

# print(pd_rawdata.columns)
column_selection = ['시도명', '소재지도로명주소', '위도', '경도']
parking_data = pd_rawdata[column_selection]
print(parking_data.head())

     시도명          소재지도로명주소         위도          경도
0  울산광역시  울산광역시 북구 명촌10길22  35.551975  129.356788
1  울산광역시  울산광역시 북구 명촌10길22  35.551975  129.356788
2  울산광역시  울산광역시 북구 명촌10길22  35.551975  129.356788
3  울산광역시  울산광역시 북구 명촌10길22  35.551975  129.356788
4  울산광역시  울산광역시 북구 명촌10길22  35.551975  129.356788

In [17]:
df1 = pd.concat((hydrant_data, parking_data), axis = 0, keys=['hydrant', 'parking'])
df1.reset_index(inplace=True)
df2 = df1.drop(['level_1'], axis = 1)
df2.columns = ['종류', '시도명', '소재지도로명주소', '위도', '경도']
df2

,종류,시도명,소재지도로명주소,위도,경도
0,hydrant,서울특별시,서울특별시 금천구 가산디지털2로 36 g밸리 더리브 스마트타워,37.471257,126.882859
1,hydrant,서울특별시,서울특별시 금천구 가산디지털1로 171 수위실,37.481101,126.881118
2,hydrant,서울특별시,서울특별시 금천구 두산로3길 49 가산동제2경노당,37.472620,126.888857
3,hydrant,서울특별시,서울특별시 금천구 벚꽃로 208 경비실,37.473484,126.886718
4,hydrant,서울특별시,서울특별시 금천구 가산디지털2로 169 수위실,37.482797,126.877303
...,...,...,...,...,...
53487,parking,울산광역시,울산광역시 울주군 범서읍 백천2길 88(굴화리),35.555881,129.252353
53488,parking,울산광역시,울산광역시 울주군 범서읍 천상3길 11(천상리),35.563268,129.227627
53489,parking,울산광역시,울산광역시 울주군 범서읍 장검길 143(굴화리),35.547636,129.249708
53490,parking,울산광역시,울산광역시 울주군 범서읍 장검길 143(굴화리),35.547636,129.249708
53491,parking,전라북도,전라북도 정읍시 첨단1로 47,35.507091,126.840867

In [29]:
g1 = df2[df2['종류'] == 'hydrant'].groupby('시도명')
s1 = g1['종류'].count()
s1.name = 'hydrant'
print(s1)

g2 = df2[df2['종류'] == 'parking'].groupby('시도명')
s2 = g2['종류'].count()
s2.name = 'parking'
print(s2)

시도명
대구광역시      130
부산광역시     6440
서울특별시    43430
Name: hydrant, dtype: int64
시도명
강원도         243
경기도         284
경상남도        111
광주광역시         8
대구광역시         6
대전광역시        58
부산광역시        18
세종특별자치시       8
울산광역시      2368
인천광역시       172
전라남도         95
전라북도         32
제주특별자치도       1
충청남도         20
충청북도         68
Name: parking, dtype: int64