### 부산광역시 이륜차 신고대수
* 출처 : 국토교통부, 자동차등록현황보고, 「이륜차신고현황_시도별 」

In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

current_font_list = matplotlib.rcParams['font.family']
font_path = "C:\Windows\Fonts\HMKMRHD.TTF"
kfont = matplotlib.font_manager.FontProperties(fname=font_path).get_name()
matplotlib.rcParams['font.family'] = [kfont] + current_font_list

In [2]:
pd_data = pd.read_csv('이륜차신고현황_시도별_20230309165417.csv', encoding='cp949')
pd_data.drop([0], axis = 0, inplace=True)
pd_data.drop(['시도명(1)'], axis = 1, inplace=True)

In [3]:
pd_data = pd_data.T

In [4]:
pd_data

            1     2     3     4      5       6        7       8
레벨01(1)    관용    관용    관용    관용    자가용     자가용      자가용     자가용
항목         경형    소형    중형    대형     경형      소형       중형      대형
금정구       5.0   4.0  68.0   2.0  345.0  2068.0   5110.0   573.0
기장군       2.0   8.0  58.0   0.0  309.0  1465.0   3417.0   627.0
남구        3.0  10.0  18.0   0.0  448.0  2398.0   6946.0   941.0
동구        2.0  22.0  32.0   1.0  183.0   941.0   2977.0   320.0
동래구       1.0   1.0  71.0   1.0  403.0  2132.0   5513.0   854.0
부산진구     10.0  21.0  86.0   1.0  623.0  3901.0  10008.0  1396.0
북구        1.0   4.0  45.0   0.0  413.0  2071.0   5487.0   720.0
사상구      26.0  38.0  96.0   1.0  550.0  2238.0   5893.0   602.0
사하구       6.0   2.0  72.0   0.0  522.0  2886.0   8096.0   969.0
서구        1.0   6.0   2.0   0.0  206.0  1480.0   4031.0   342.0
수영구       0.0   4.0  80.0   1.0  307.0  1468.0   4217.0   674.0
연제구       5.0   4.0  89.0  36.0  274.0  1587.0   4362.0   645.0
영도구       5.0   2.0  43.0   0.0  216.0  1480.0   4331.0   344.0
해운대구      7.0   2.0  86.0   1.0  537.0  2924.0   7902.0  1332.0
부산기타      0.0   0.0   0.0   0.0    0.0    10.0      2.0     0.0

In [5]:
col = ['지역','관용(경형)','관용(소형)','관용(중형)','관용(대형)','자가용(경형)','자가용(소형)','자가용(중형)','자가용(대형)']

In [6]:
pd_data.drop(['레벨01(1)', '항목'], axis = 0, inplace=True)
pd_data

         1     2     3     4      5       6        7       8
금정구    5.0   4.0  68.0   2.0  345.0  2068.0   5110.0   573.0
기장군    2.0   8.0  58.0   0.0  309.0  1465.0   3417.0   627.0
남구     3.0  10.0  18.0   0.0  448.0  2398.0   6946.0   941.0
동구     2.0  22.0  32.0   1.0  183.0   941.0   2977.0   320.0
동래구    1.0   1.0  71.0   1.0  403.0  2132.0   5513.0   854.0
부산진구  10.0  21.0  86.0   1.0  623.0  3901.0  10008.0  1396.0
북구     1.0   4.0  45.0   0.0  413.0  2071.0   5487.0   720.0
사상구   26.0  38.0  96.0   1.0  550.0  2238.0   5893.0   602.0
사하구    6.0   2.0  72.0   0.0  522.0  2886.0   8096.0   969.0
서구     1.0   6.0   2.0   0.0  206.0  1480.0   4031.0   342.0
수영구    0.0   4.0  80.0   1.0  307.0  1468.0   4217.0   674.0
연제구    5.0   4.0  89.0  36.0  274.0  1587.0   4362.0   645.0
영도구    5.0   2.0  43.0   0.0  216.0  1480.0   4331.0   344.0
해운대구   7.0   2.0  86.0   1.0  537.0  2924.0   7902.0  1332.0
부산기타   0.0   0.0   0.0   0.0    0.0    10.0      2.0     0.0

In [9]:
pd_data = pd_data.reset_index()
pd_data.columns = col
pd_data

      지역 관용(경형) 관용(소형) 관용(중형) 관용(대형) 자가용(경형) 자가용(소형)  자가용(중형) 자가용(대형)
0    금정구    5.0    4.0   68.0    2.0   345.0  2068.0   5110.0   573.0
1    기장군    2.0    8.0   58.0    0.0   309.0  1465.0   3417.0   627.0
2     남구    3.0   10.0   18.0    0.0   448.0  2398.0   6946.0   941.0
3     동구    2.0   22.0   32.0    1.0   183.0   941.0   2977.0   320.0
4    동래구    1.0    1.0   71.0    1.0   403.0  2132.0   5513.0   854.0
5   부산진구   10.0   21.0   86.0    1.0   623.0  3901.0  10008.0  1396.0
6     북구    1.0    4.0   45.0    0.0   413.0  2071.0   5487.0   720.0
7    사상구   26.0   38.0   96.0    1.0   550.0  2238.0   5893.0   602.0
8    사하구    6.0    2.0   72.0    0.0   522.0  2886.0   8096.0   969.0
9     서구    1.0    6.0    2.0    0.0   206.0  1480.0   4031.0   342.0
10   수영구    0.0    4.0   80.0    1.0   307.0  1468.0   4217.0   674.0
11   연제구    5.0    4.0   89.0   36.0   274.0  1587.0   4362.0   645.0
12   영도구    5.0    2.0   43.0    0.0   216.0  1480.0   4331.0   344.0
13  해운대구    7.0    2.0   86.0    1.0   537.0  2924.0   7902.0  1332.0
14  부산기타    0.0    0.0    0.0    0.0     0.0    10.0      2.0     0.0

C:\Users\ITPS\AppData\Local\Temp\ipykernel_4884\2109452361.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  pd_data.pivot('지역', '관용 (경험)')

KeyError: "None of ['관용 (경험)'] are in the columns"